user_edit:
  path: /user/{_id}
  defaults: { _controller: App\Controller\RoutingController::edit }
  requirements:
    id: '\d+'

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number