#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_annotations:
    resource: '../src/Controller/'
    type: annotation

user_edit:
  path: /user/{_id}
  defaults: { _controller: App\Controller\RoutingController::edit }
  requirements:
    _id: '\d+'

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

user_list:
  path: /user/list/{_page}
  defaults: { _controller: App\Controller\RoutingController::list, _page: 1, _title: 'Lista de usuarios' }
  requirements:
    id: '\d+'

mobile_homepage:
  path: /
  controller: App\Controller\RoutingController::mobileHomepage
  host: m.trainingit.es

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /user/list
    permanent: true

otra:
  path: /otra
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: user_list
    permanent: true

generate_url:
  path: /generate_url
  defaults: { _controller: App\Controller\RoutingController::generarURL }

output_escaping:
  path: /output_escaping
  defaults: { _controller: App\Controller\TwigController::outputEscaping }

output_format:
  path: /output_format/{_slug}/{_format}
  defaults: { _controller: App\Controller\TwigController::showFormat }

article_detail:
  path: /article/{_locale}/{_year}/{_slug}.{_format}
  defaults: { _controller: App\Controller\BlogController::articleDetail, _format: html }
  requirements:
    _locale:  es|en|fr
    _format: html|rss

price:
  path: /price
  controller: App\Controller\TwigController::price
